config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get '/' => 'sessions#welcome'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/signup' => 'users#new'
get '/auth/google_oauth2/callback' => 'sessions#omniauth'
delete '/logout' => 'sessions#destroy'


resources :essays do
  resources :responses, only: [:new, :show, :index, :edit]
end 
get '/recent', to: 'essays#recent', as: 'recent'
resources :users
resources :books
resources :responses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :essays
    validates :title, presence: true, uniqueness: true 
    validates :author, presence: true, uniqueness: true
end

app/models/essay.rb
class Essay < ApplicationRecord
    belongs_to :user
    belongs_to :book
    has_many :responses
    has_many :responders, through: :responses, source: :user 
    accepts_nested_attributes_for :book 
    validates :title, presence: true 
    validates :content, presence: true 
    scope :recent, lambda { where('created_at >= ?', Time.now - 1.week) }

    def book_attributes=(attributes)
        self.book = Book.find_or_create_by(attributes) if !attributes['title'].empty? && !attributes['author'].empty?
        self.book
    end
end

app/models/response.rb
class Response < ApplicationRecord 
    belongs_to :user 
    belongs_to :essay
    validates :content, presence: true 
end

app/models/user.rb
class User < ApplicationRecord 
    has_many :essays
    has_many :responses
    has_many :essay_responses, through: :responses, source: :essay
    validates :name, presence: true
    validates :email, presence: true
    has_secure_password

    def self.create_by_omniauth(auth)
        self.find_or_create_by(email: auth[:info][:email]) do |u|
            u.name = auth[:info][:email]
            u.password = SecureRandom.hex
        end 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private 

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def if_not_logged_in
        if !logged_in?
            redirect_to login_path
        end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index 
        @books = Book.all
    end

    def show
        @book = Book.find_by_id(params[:id])
    end 

end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController 
    before_action :set_essay, only:[:show, :edit, :update]
    before_action :if_not_logged_in

    def new 
        @essay = Essay.new 
        @essay.build_book 
    end 

    def create
        @essay = Essay.new(essay_params)
        @essay.user_id = session[:user_id]
        if @essay.save
            redirect_to essay_path(@essay)
        else 
            @essay.build_book 
            render :new 
        end 
    end

    def show
        if !set_essay  
            redirect_to essays_path
        end
    end 

    def index
        @essays = Essay.all
    end

    def recent 
        @essays = Essay.all.recent
    end

    def edit 
        if current_user.id == @essay.user_id 
        else 
            redirect_to essays_path
        end 
    end

    def update 
        if @essay.update(essay_params)
            redirect_to essay_path(@essay)
        else 
            render :edit 
        end
    end 

    def destroy 
        set_essay 
        if @essay.present?
            @essay.destroy
            redirect_to user_path(@essay.user)
        end
    end

    private 

    def essay_params 
        params.require(:essay).permit(:title, :content, :book_id, book_attributes: [:title, :author])
    end

    def set_essay
        @essay = Essay.find_by_id(params[:id])
    end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
    before_action :if_not_logged_in
    before_action :set_response, only:[:show, :edit, :update, :destroy]

    def new
        if @essay = Essay.find_by_id(params[:essay_id]) 
            @response = @essay.responses.build
        else 
            @response = Response.new
        end 
    end

    def create
        @response = current_user.responses.build(response_params)
        if @response.save
            redirect_to response_path(@response)
        else 
            render :new 
        end 
    end

    def index 
        @responses = Response.all
    end 

    def show 
        @response = Response.find_by_id(params[:id])
    end 

    def edit 
        if current_user.id == @response.user_id 
        else 
            redirect_to responses_path
        end 
    end

    def update 
        if @response.update(response_params)
            redirect_to response_path(@response)
        else 
            render :edit 
        end
    end 

    def destroy 
        @response.destroy
        redirect_to user_path(@response.user)
    end

    private

    def response_params
        params.require(:response).permit(:essay_id, :content)
    end 
    
    def set_response
        @response = Response.find_by_id(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
    end

    def new
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            flash[:error] = "Invalid Entry"
            redirect_to login_path
        end
    end

    def omniauth 
        @user = User.create_by_omniauth(auth)
        session[:user_id] = @user.id 
        redirect_to user_path(@user)
    end


    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private 

    def auth 
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    def new 
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else 
            render :new
        end 
    end

    def show 
        if_not_logged_in
        @user = User.find_by_id(params[:id]) 
        redirect_to '/' if !@user
    end

    private 

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>Books</h1>

<% @books.each do |book| %>
    <h3><%= book.title %></h3>
    <p>By <em><%= link_to book.author, book_path(book) %></p><br><br>
<% end %>

app/views/books/show.html.erb
<h1 class="mt-3 mb-5">Essays Concerning <%= @book.author %>:</h1>

<% @book.essays.each do |essay| %>
    <h3><%= link_to essay.title, essay_path(essay) %></h3>
    <p><em><%= essay.content %></p>
    <h6 class="mb-5">By: <%= essay.user.name %></h6><br><br>
<% end %>

app/views/essays/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @essay} %>

<%= form_for(@essay) do |f| %>

    <div class="form-group">
    <%= f.label :title %>:
    <%= f.text_field :title, class: "form-control" %><br><br>
    <%= f.label :content %>:
    <%= f.text_area :content, class: "form-control" %><br><br>
    </div>

    <div class="form-group">
    <p> Select a Book this Essay Concerns: 

    <%= f.collection_select :book_id, Book.all, :id, :title, {include_blank: 'Select One'}, {class: "form-control"} %></p>
    
    <p> Or Add a New Book

    <%= f.fields_for :book do |b| %>
        <p><%= b.label :title %>:
        <%= b.text_field :title, class: "form-control" %></p>
        <p><%= b.label :author %>:
        <%= b.text_field :author, class: "form-control" %></p></p>
    </div>

    <% end %>
    
    <%= f.submit 'Create Essay', :class => "btn btn-primary" %>
<% end %>

app/views/essays/edit.html.erb
<h1>Edit Essay</h1>

<%= render partial: 'form' %>

app/views/essays/index.html.erb
<h1>Essays</h1>

<% @essays.each do |essay| %>
    <div class="card">
    <h3 class="card-title"><%= link_to essay.title, essay_path(essay) %></h3>
    <p class="card-text"><em><%= essay.content %></p>
    <h6 class="card-subtitle">By:<%= essay.user.name %></h6>
    </div>
<% end %>

app/views/essays/new.html.erb
<h1>Write a New Essay<h1>

<%= render partial: 'form' %>

app/views/essays/recent.html.erb
<h1 class="mb-5">Recent Essays</h1>

<% @essays.each do |essay| %>
    <h3><%= link_to essay.title, essay_path(essay) %></h3>
    <p><em><%= essay.content %></p>
    <h6 class="mb-5">By:<%= essay.user.name %></h6>
<% end %>

app/views/essays/show.html.erb
<h2 class="mt-3 mb-5"><strong><%= @essay.title %></strong><h2>
<p><em><%= @essay.content %></em</p><br><br>
<h3>By: <%= @essay.user.name %></h3><br>

<h3><%= link_to "Respond to this Essay", new_essay_response_path(@essay) %><br><br></h3>
<p><%= link_to "Edit Essay", edit_essay_path(@essay), :class => "btn btn-primary" if @essay.user == current_user %><br></p>
<p><%= button_to "Delete Essay", essay_path(@essay), :class => "btn btn-primary", method: :delete if @essay.user == current_user %></p>



<h1 class="mb-3">Responses:</h1>

<% @essay.responses.each do |response| %>
    <ul>
    <li><h3><%= response.content %></h3></li>
    <p class="mb-5">Written by: <%=response.user.name%></p>
    </ul> 
<% end %>


    

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |message| %>
        <li class="alert alert-danger"><%= message %></li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiteraryEssaysRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if logged_in? %>
      <ul class="nav">
        <li class="nav-item mx-auto btn btn-light"><%= link_to "Home", user_path(session[:user_id])%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "Write a new Essay", new_essay_path%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "Recent Essays", recent_path%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "All Essays", essays_path%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "All Responses", responses_path%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "All Books", books_path%></li>
        <li class="nav-item mx-auto btn btn-light"><%= link_to "Logout", logout_path, method: :delete%></li>
      </ul>
  <% end %>


  <body>

  <div class="container">
    <%= yield %>
  </div>
    
  </body>
</html>

app/views/responses/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @response} %>

<%= form_for(@response) do |f| %>
    <div class="form-group">
    <%= f.hidden_field :essay_id %>
    <p><%= f.label :content %>:<p>
    <%= f.text_area :content, class: "form-control"%>
    <p><%= f.submit 'Create Response', :class => "btn btn-primary" %></p>
    </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Edit this Response</h1>

<%= render partial: 'form' %>

app/views/responses/index.html.erb
<h1 class="mt-3 mb-3">All Responses</h1>

    <% @responses.each do |response| %>
        <div class="card"
        <p>Responding to: <%= link_to response.essay.title, essay_path(response.essay) %></p>
        <p class="card-subtitle"><%= response.user.name %> wrote:</p>
        <h3 class="card-text mt-3 mb-3"><%= response.content %></h3>
        <p><%= link_to "Response Show Page", response_path(response) %><p>
        </div>
    <% end %>

app/views/responses/new.html.erb
<h1 class="mt-3 mb-3">Create A Response</h1>

<%= render partial: 'form' %>

app/views/responses/show.html.erb
<h3><em>Original Essay: </em><%= @response.essay.title %><br><br></h3>
<p>Response: <%= @response.content %><br><br></p>
<p> Written by: <%= @response.user.name %></p>

<%= link_to "Edit Response", edit_response_path(@response) if @response.user == current_user %><br>
<%= button_to "Delete Response", response_path(@response), method: :delete if @response.user == current_user %>

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @user} %>

<h1>Signup</h1>

<div class="form-group">
<%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :email %>
    <%= f.text_field :email %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Sign Up", :class => "btn btn-primary" %>
<% end %>

<br><br>

<%= link_to "Back", '/', :class => "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<h1 class="mt-3 mb-3"><%= @user.name%>'s Home</h1>

<h2 class="mb-3"><%= @user.name%>'s Essays:</h2>
    <% @user.essays.each do |essay|%>
        
        <h2><%= essay.title %></h3>
        <p><%= essay.content %></p>
        
    <% end %>

    <br><br>

<h3 class="mb-3"><%= @user.name%>'s Responses:</h3>

    <% @user.responses.each do |response|%>
        <ul>
        <li><p><%= response.content %></p></li>
        <p class="mb-3"><strong>(Written in response to: <%= link_to response.essay.title, essay_path(response)%>)</strong></p><br><br>
        </ul>
    <% end %>
        